name: Apply patch from Issue

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  apply-patch:
    if: contains(join(fromJson(toJson(github.event.issue.labels)).*.name), 'apply-patch')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract patch
        id: extract
        run: |
          echo "${{ github.event.issue.body }}" > issue.txt
          sed -n '/```diff/,/```/p' issue.txt | sed '1d;$d' > incoming.patch
          echo "branch=patch-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Apply patch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git checkout -b "${{ steps.extract.outputs.branch }}"
          git apply -p0 --whitespace=fix incoming.patch || true
          git add -A || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Apply patch from issue #${{ github.event.issue.number }}"
          git push --set-upstream origin "${{ steps.extract.outputs.branch }}"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "${{ steps.extract.outputs.branch }}"
          base: main
          title: "Apply patch from issue #${{ github.event.issue.number }}"
          body: "Automated PR created from a patch in the issue."
