name: Apply patch from Issue (robust)

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

jobs:
  apply-patch:
    # ラベル apply-patch が付いた Issue（またはそのコメント）のときだけ動く
    if: >
      (github.event_name == 'issues' &&
       contains(join(fromJson(toJson(github.event.issue.labels)).*.name), 'apply-patch'))
      || (github.event_name == 'issue_comment' &&
          github.event.issue.state == 'open' &&
          contains(join(fromJson(toJson(github.event.issue.labels)).*.name), 'apply-patch'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract patch block (```diff or ```patch)
        id: extract
        env:
          BODY_ISSUE: ${{ github.event.issue.body }}
          BODY_COMMENT: ${{ github.event.comment.body || '' }}
        run: |
          set -e
          if [ -n "$BODY_COMMENT" ]; then
            printf "%s" "$BODY_COMMENT" > body.txt
          else
            printf "%s" "$BODY_ISSUE" > body.txt
          fi

          python3 - << 'PY'
import re, sys, pathlib
text = pathlib.Path("body.txt").read_text()
# 行頭の空白許容、```diff / ```patch のどちらでもOK。閉じは ``` 単独行。
pat = re.compile(r'^[ \t]*```(?:diff|patch)[ \t]*\r?\n(.*?)[ \t]*```[ \t]*$',
                 re.DOTALL | re.MULTILINE)
m = pat.search(text)
if not m:
    # 見つからなければ空ファイルを作成
    pathlib.Path("incoming.patch").write_text("")
    sys.exit(0)
pathlib.Path("incoming.patch").write_text(m.group(1))
PY

          if [ -s incoming.patch ]; then
            echo "found=1" >> $GITHUB_OUTPUT
          else
            echo "found=0" >> $GITHUB_OUTPUT
          fi
          echo "branch=patch-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Comment if no patch found
        if: steps.extract.outputs.found != '1'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "⚠️ ` ```diff ` または ` ```patch ` のコードブロックが見つかりま
