name: Apply patch from Issue

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

jobs:
  apply-patch:
    # ラベル apply-patch が付いた Issue/コメントのみ反応
    if: >
      (github.event_name == 'issues' &&
       contains(join(fromJson(toJson(github.event.issue.labels)).*.name), 'apply-patch'))
      || (github.event_name == 'issue_comment' &&
          github.event.issue.state == 'open' &&
          contains(join(fromJson(toJson(github.event.issue.labels)).*.name), 'apply-patch'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const fs = require('fs');
            const body = context.payload.comment ? context.payload.comment.body : context.payload.issue.body;
            const m = body && body.match(/```(?:diff|patch)\n([\s\S]*?)```/);
            if (!m) core.setFailed('No ```diff``` block found.');
            fs.writeFileSync('incoming.patch', m[1], 'utf8');
            core.setOutput('branch', `patch/${context.runId}`);

      - name: Apply patch and push
        run: |
          set -e
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git checkout -b "${{ steps.extract.outputs.branch }}"
          # リポジトリ直下のパスを想定 (-p0)
          git apply -p0 --whitespace=fix incoming.patch || (git apply -p0 --reject incoming.patch && echo "::warning::Some hunks failed; .rej files created")
          git add -A || true
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0
          fi
          git commit -m "Apply patch from issue #${{ github.event.issue.number }}"
          git push --set-upstream origin "${{ steps.extract.outputs.branch }}"

      - name: Open PR
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.rest.pulls.create({
              owner, repo,
              title: `Apply patch from issue #${{ github.event.issue.number }}`,
              head: '${{ steps.extract.outputs.branch }}',
              base: 'main',
              body: 'Automated PR from patch in the issue.'
            });
