name: Apply .patch on push

on:
  push:
    paths:
      - 'patches/*.patch'   # ← patches フォルダ配下に .patch を置いた時だけ動く

jobs:
  apply-patch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Find latest patch file in this push
        id: pick
        run: |
          set -e
          # 直近のpushで追加/変更された .patch を拾う
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^patches/.*\.patch$' | tail -n1 > PATCH_FILE || true
          if [ ! -s PATCH_FILE ]; then
            echo "No patch file changed. Exiting."; exit 1
          fi
          echo "file=$(cat PATCH_FILE)" >> $GITHUB_OUTPUT
          echo "Picked patch: $(cat PATCH_FILE)"

      - name: Create branch and apply patch
        run: |
          set -e
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          BRANCH="patch/${GITHUB_RUN_ID}"
          git checkout -b "$BRANCH"

          PATCH="${{ steps.pick.outputs.file }}"
          # まず -p0 でトライ、ダメなら -p1 で .rej を出さずトライ
          if git apply -p0 --whitespace=fix "$PATCH"; then
            echo "Applied with -p0"
          elif git apply -p1 --whitespace=fix "$PATCH"; then
            echo "Applied with -p1"
          else
            echo "Patch failed"; exit 1
          fi

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 1
          fi
          git commit -m "Apply patch: $PATCH"
          git push --set-upstream origin "$BRANCH"

      - name: Open PR
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.rest.pulls.create({
              owner, repo,
              title: 'Apply patch from patches/',
              head: process.env.BRANCH || 'patch/' + process.env.GITHUB_RUN_ID,
              base: 'main',
              body: 'Automated PR created from a .patch file in patches/.'
            });
