name: Apply .patch on push (robust & secure)

on:
  # pushイベントで、パッチファイルが変更されたときのみに実行
  push:
    paths:
      - 'patches/*.patch'
      
jobs:
  apply-patch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    # ワークフローを実行するコミットが、ボットによるものでないことを確認
    # これにより、無限ループを回避します
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pick latest patch file
        id: pick
        run: |
          set -e
          ls -1t patches/*.patch | head -n1 > PATCH_FILE
          FILE=$(cat PATCH_FILE)
          echo "Picked: $FILE"
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Create branch & apply
        id: apply
        run: |
          set -e
          git config user.email "actions@github.com"
          git config user.name  "github-actions[bot]"
          BRANCH="patch/${GITHUB_RUN_ID}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          git checkout -b "$BRANCH"

          PATCH="${{ steps.pick.outputs.file }}"
          echo "Applying $PATCH"

          if git apply -p0 --whitespace=fix "$PATCH"; then
            echo "Applied with -p0"
          elif git apply -p1 --whitespace=fix "$PATCH"; then
            echo "Applied with -p1"
          else
            echo "Patch failed"
            exit 1
          fi

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit (patch had no effect)"
            exit 1
          fi

          git commit -m "Apply patch: $PATCH"
          git push --set-upstream origin "$BRANCH"

      - name: Open PR
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.rest.pulls.create({
              owner, repo,
              title: 'Apply patch from patches/',
              head: '${{ steps.apply.outputs.branch }}',
              base: 'main',
              body: 'Automated PR created from the latest .patch in patches/.'
            });
